version: "3.8"
services:
  api:
    image: venttys-graphql
    build: .
    environment:
      - PORT=80
      - ENV=development
      - DATABASE_SERVER='mongodb://venttys:dmVudHR5cw@venttys-mongo/venttys?authSource=admin'
    volumes: 
      - ./public:/home/app/public
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 80:80
    networks: 
      - venttys-net

networks: 
  venttys-net:
    name: venttys-net